name: Build Docker Image

on: [push, pull-request]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get the tag
        run: |
          if [[ $GITHUB_REF == refs/tags* ]]
          then
            echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=ignore" >> $GITHUB_ENV
          fi
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: jamieleecho/coco-dev:${{ env.RELEASE_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
